version: "3.8"

networks:
    erp-app:
        driver: bridge

services:

    database:
        image: mysql:latest
        container_name: mysql_db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        expose:
            - 3306
        ports:
            - 3306:3306
        env_file: ./env/database.env
        volumes: 
            - ./scripts/createDB.sql:/docker-entrypoint-initdb.d/createDB.sql
        networks:
            - erp-app

    frontend:
        build:
            context: ./frontend
        stdin_open: true
        ports:
            - 3000:3000
        env_file: ./env/frontend.env
        networks:
            - erp-app

    backend:
        depends_on: 
            - database
        build:
            context: ./backend
            target: develop
        ports:
            - 5000:5000
        env_file: ./env/backend.env
        networks:
            - erp-app
