name: CI Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install Dependencies
      working-directory: ./backend
      run: npm ci
    - name: Linting Check
      working-directory: ./backend
      run: npx prettier --check .
    - name: Coverage Check
      working-directory: ./backend
      run: npm run coverage
    - name: Build
      working-directory: ./backend
      run: npm run build
  