name: CI/CD Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  naming:
    name: Naming convention check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check branch naming convention
      uses: deepakputhraya/action-branch-name@master
      with:
        regex: '^(BUG|FEAT|CHORE|DOC|TASK)-\d+\/[a-zA-Z0-9_]+$'
        allowed_prefixes: 'BUG,FEAT,CHORE,DOC,TASK'
        ignore: main
        min_length: 5
        max_length: 30
    - name: Check commit message naming convention
      uses: gsactions/commit-message-checker@v1
      with:
        pattern: '^(BUG|FEAT|CHORE|DOC|TASK)-\d+:[a-zA-Z0-9_ ]+$'
        flags: 'gm'
        error: 'Commit message does not follow the naming convention'

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install Dependencies
      working-directory: ./backend
      run: npm ci
    - name: Linting Check
      working-directory: ./backend
      run: npx prettier --check .
    - name: Coverage Check
      working-directory: ./backend
      run: npm run coverage
    - name: Build
      working-directory: ./backend
      run: npm run build
  